### ISSUE TITLE
Descobrir por que ammonite está lançando excessão quando usamos o Jupyter

### ISSUE THREAD

**Issue by joao-parana** [joao-parana/spark#2]
Descobrir por que ammonite está lançando a excessão abaixo quando usamos o Jupyter

```
Exception in thread "main" java.lang.RuntimeException: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  file:/root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar: not found: /root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:174)
	at jupyter.scala.JupyterScalaApp.delayedEndpoint$jupyter$scala$JupyterScalaApp$1(JupyterScala.scala:93)
	at jupyter.scala.JupyterScalaApp$delayedInit$body.apply(JupyterScala.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:381)
	. . . 
```

**Caused by:**

```
Caused by: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  file:/root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar: not found: /root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar
	at ammonite.runtime.tools.DependencyThing.resolveArtifact(DependencyThing.scala:106)
	at ammonite.runtime.Interpreter.loadIvy(Interpreter.scala:630)
	at ammonite.runtime.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:655)
	at jupyter.scala.Interp.<init>(Interp.scala:75)
	. . . 
```

**Comment by joao-parana** [comment]
Veja se tem alguma issue relativa a isso em [https://github.com/alexarchambault/jupyter-scala](https://github.com/alexarchambault/jupyter-scala)
